// let profs = mockcourse.courses.map((coursesPage)=>{
//     return coursesPage.professor
// })
// console.log(profs)

export const mockcourse = {
  courses: [
    {
      uuid: "61b3e62f-7fa9-4b0a-a069-4242cf1aa7cb",
      courseTitle: "Introduction to Computer Science",
      professor: "Dr. Jane Smith",
      startDate: "2023-09-01",
      endDate: "2023-12-15",
      season: "Fall",
      description:
        "This course introduces the fundamental principles of computer science, including programming concepts, algorithms, and data structures. Students will gain hands-on experience with a variety of programming languages and tools.",
      studyType: "full-time",
      totalSeats: 50,
      seatsFilled: 35,
      contactHours: 15,
      school: ["School of Computer Science"],
    },
    {
      uuid: "b81f2488-3d3e-44d5-b5d5-b99f3d5e5e1d",
      courseTitle: "Marketing Fundamentals",
      professor: "Dr. John Doe",
      startDate: "2023-09-15",
      endDate: "2023-12-15",
      season: "Fall",
      description:
        "This course covers the basics of marketing, including market research, advertising, and branding. Students will learn how to develop effective marketing strategies for products and services.",
      studyType: "part-time",
      totalSeats: 30,
      seatsFilled: 20,
      contactHours: 12,
      school: ["School of Business"],
    },
    {
      uuid: "1b050317-0d18-4d89-992e-1fa1e94e3666",
      courseTitle: "Financial Accounting",
      professor: "Dr. Sarah Lee",
      startDate: "2023-10-01",
      endDate: "2023-12-15",
      season: "Fall",
      description:
        "This course covers the principles of financial accounting, including balance sheets, income statements, and cash flow statements. Students will learn how to analyze financial statements and make informed business decisions.",
      studyType: "full-time",
      totalSeats: 40,
      seatsFilled: 38,
      contactHours: 18,
      school: ["School of Business", "School of Accounting"],
    },
    {
      uuid: "947c16f2-2b44-4d56-a12f-1b7a62a14010",
      courseTitle: "Creative Writing Workshop",
      professor: "Prof. Emily Johnson",
      startDate: "2023-10-15",
      endDate: "2023-12-15",
      season: "Fall",
      description:
        "This course is designed for aspiring writers who want to develop their craft. Students will learn how to write effective dialogue, create compelling characters, and use literary devices to enhance their writing.",
      studyType: "part-time",
      totalSeats: 20,
      seatsFilled: 18,
      contactHours: 10,
      school: ["School of Arts and Humanities"],
    },
    {
      uuid: "f26d46aa-6ec5-4760-bb08-5f6f290508fd",
      courseTitle: "Artificial Intelligence",
      professor: "Dr. Robert Johnson",
      startDate: "2024-01-15",
      endDate: "2024-04-15",
      season: "Spring",
      description:
        "This course covers the basics of artificial intelligence, including machine learning algorithms, natural language processing, and computer vision. Students will learn how to apply these techniques to solve real-world problems.",
      studyType: "full-time",
      totalSeats: 60,
      seatsFilled: 50,
      contactHours: 20,
      school: ["School of Computer Science"],
    },
    {
      uuid: "85f5dc6b-0f34-4166-95ed-cb39a018d7f3",
      courseTitle: "International Business",
      professor: "Dr. Elizabeth Kim",
      startDate: "2024-02-01",
      endDate: "2024-05-15",
      season: "Spring",
      description:
        "This course explores the challenges and opportunities of doing business in a global environment. Students will learn how to develop international strategies, manage cross-cultural teams, and navigate legal and regulatory issues.",
      studyType: "part-time",
      totalSeats: 35,
      seatsFilled: 25,
      contactHours: 14,
      school: ["School of Business"],
    },
    {
      uuid: "d3a3f0c3-2e7e-4cf5-b930-755f5caee19c",
      courseTitle: "Organic Chemistry",
      professor: "Dr. Michael Lee",
      startDate: "2024-03-01",
      endDate: "2024-06-15",
      season: "Spring",
      description:
        "This course covers the principles of organic chemistry, including functional groups, nomenclature, and reactions. Students will learn how to apply these principles to synthesize organic molecules.",
      studyType: "full-time",
      totalSeats: 45,
      seatsFilled: 40,
      contactHours: 22,
      school: ["School of Chemistry"],
    },
    {
      uuid: "9d03c7d9-7645-4c29-b3f8-1627e39e2a1b",
      courseTitle: "Applied Statistics",
      professor: "Dr. James Smith",
      startDate: "2024-03-15",
      endDate: "2024-06-15",
      season: "Spring",
      description:
        "This course covers the basics of applied statistics, including probability theory, hypothesis testing, and regression analysis. Students will learn how to apply these techniques to analyze data and make informed decisions.",
      studyType: "part-time",
      totalSeats: 25,
      seatsFilled: 20,
      contactHours: 12,
      school: ["School of Mathematics", "School of Business"],
    },
    {
      uuid: "5abdfc87-1f4d-4d93-af4b-ff3e3c3c1bf3",
      courseTitle: "Environmental Science",
      professor: "Dr. Jane Adams",
      startDate: "2023-09-01",
      endDate: "2023-12-01",
      season: "Fall",
      description:
        "This course introduces students to the basic principles of environmental science, including ecological systems, environmental management, and sustainability. Students will also learn about climate change and other environmental issues affecting the planet today.",
      studyType: "full-time",
      totalSeats: 50,
      seatsFilled: 30,
      contactHours: 18,
      school: ["School of Biology"],
    },
    {
      uuid: "99a06b90-8c2e-48d2-a755-07db63f40e7f",
      courseTitle: "Digital Marketing",
      professor: "Dr. David Kim",
      startDate: "2024-02-15",
      endDate: "2024-05-15",
      season: "Spring",
      description:
        "This course covers the fundamentals of digital marketing, including SEO, SEM, email marketing, social media marketing, and content marketing. Students will learn how to develop effective digital marketing strategies and measure their success using key performance indicators.",
      studyType: "full-time",
      totalSeats: 40,
      seatsFilled: 20,
      contactHours: 20,
      school: ["School of Business"],
    },
    {
      uuid: "cb00efc9-42af-4f27-a2db-5a5f5d5ddcc8",
      courseTitle: "Applied Mathematics",
      professor: "Dr. Maria Hernandez",
      startDate: "2024-06-01",
      endDate: "2024-09-01",
      season: "Summer",
      description:
        "This course covers advanced topics in applied mathematics, including optimization, differential equations, and linear algebra. Students will learn how to apply mathematical techniques to solve real-world problems in fields such as engineering, physics, and economics.",
      studyType: "part-time",
      totalSeats: 30,
      seatsFilled: 10,
      contactHours: 12,
      school: ["School of Mathematics"],
    },
    {
      uuid: "fa74088c-8c16-4cd2-9a14-9e9c8b3d3a3f",
      courseTitle: "Social Psychology",
      professor: "Dr. Sarah Johnson",
      startDate: "2024-09-15",
      endDate: "2024-12-15",
      season: "Fall",
      description:
        "This course introduces students to the basic principles of social psychology, including group dynamics, social influence, and intergroup relations. Students will also learn about social cognition and how it relates to individual behavior.",
      studyType: "part-time",
      totalSeats: 25,
      seatsFilled: 10,
      contactHours: 15,
      school: ["School of Social Sciences"],
    },
    {
      uuid: "321a8f71-7d77-4b64-a7c6-461b41f7b1c8",
      courseTitle: "Robotics Engineering",
      professor: "Dr. Michael Lee",
      startDate: "2025-01-01",
      endDate: "2025-04-01",
      season: "Spring",
      description:
        "This course covers the fundamentals of robotics engineering, including kinematics, dynamics, and control. Students will also learn about robotic sensors and actuators, as well as robot programming languages such as ROS and MATLAB.",
      studyType: "full-time",
      totalSeats: 35,
      seatsFilled: 15,
      contactHours: 20,
      school: ["School of Engineering"],
    },
    {
      uuid: "7dbfb8c8-27a9-442d-97bb-303af8c8fa09",
      courseTitle: "Cognitive Neuroscience",
      professor: "Dr. Elizabeth Smith",
      startDate: "2025-09-01",
      endDate: "2025-12-01",
      season: "Fall",
      description:
        "This course covers the basic principles of cognitive neuroscience, including the structure and function of the brain, sensation and perception, and memory and attention. Students will also learn about neuroimaging techniques and their applications in cognitive neuroscience research.",
      studyType: "part-time",
      totalSeats: 20,
      seatsFilled: 5,
      contactHours: 15,
      school: ["School of Psychology", "School of Biology"],
    },
    {
      uuid: "23c3b955-d8b9-40ed-b41d-2d562ff0352a",
      courseTitle: "International Relations",
      professor: "Dr. John Davis",
      startDate: "2024-06-01",
      endDate: "2024-09-01",
      season: "Summer",
      description:
        "This course covers the basic principles of international relations, including the history of the international system, international security, and international political economy. Students will also learn about the role of international organizations and the challenges of global governance.",
      studyType: "full-time",
      totalSeats: 30,
      seatsFilled: 20,
      contactHours: 25,
      school: ["School of International Studies"],
    },
    {
      uuid: "c32c2d2a-8316-41a7-ae29-9aa9cc64c8ba",
      courseTitle: "Data Mining and Machine Learning",
      professor: "Dr. Richard Johnson",
      startDate: "2024-02-15",
      endDate: "2024-05-15",
      season: "Spring",
      description:
        "This course covers the fundamental concepts and algorithms of data mining and machine learning, including supervised and unsupervised learning, decision trees, and clustering. Students will also learn about data preprocessing and feature selection, as well as performance evaluation and model selection.",
      studyType: "part-time",
      totalSeats: 25,
      seatsFilled: 10,
      contactHours: 18,
      school: ["School of Computer Science"],
    },
    {
      uuid: "fd0e00d8-9e9a-4ca9-9a7d-8d2b59c118ed",
      courseTitle: "Contemporary Art History",
      professor: "Dr. Laura Kim",
      startDate: "2023-09-01",
      endDate: "2023-12-01",
      season: "Fall",
      description:
        "This course explores the history of contemporary art, including postmodernism, conceptualism, and performance art. Students will also learn about the impact of globalization and digital media on contemporary art practices.",
      studyType: "part-time",
      totalSeats: 15,
      seatsFilled: 10,
      contactHours: 12,
      school: ["School of Art", "School of Humanities"],
    },
    {
      uuid: "54c3dc12-2a0e-4cc1-9b07-3ef9782f312c",
      courseTitle: "Green Energy Technologies",
      professor: "Dr. Sarah Lee",
      startDate: "2024-03-01",
      endDate: "2024-06-01",
      season: "Spring",
      description:
        "This course covers the fundamental principles of green energy technologies, including solar, wind, and geothermal energy. Students will also learn about energy storage and distribution, as well as the economic and environmental impacts of green energy.",
      studyType: "full-time",
      totalSeats: 20,
      seatsFilled: 5,
      contactHours: 20,
      school: ["School of Energy and Environmental Studies"],
    },
    {
      uuid: "ee6bf928-6c43-4bb8-b44a-27d7d42af15a",
      courseTitle: "Human-Computer Interaction",
      professor: "Dr. Mark Chen",
      startDate: "2024-09-01",
      endDate: "2024-12-01",
      season: "Fall",
      description:
        "This course covers the principles and methods of human-computer interaction, including user interface design, usability evaluation, and cognitive models. Students will also learn about the social and ethical issues in human-computer interaction research.",
      studyType: "part-time",
      totalSeats: 25,
      seatsFilled: 10,
      contactHours: 15,
      school: ["School of Computer Science", "School of Psychology"],
    },
    {
      uuid: "57fc6f8d-85e2-414d-a49f-83f20b27d105",
      courseTitle: "Introduction to Astrophysics",
      professor: "Dr. James Brown",
      startDate: "2024-06-01",
      endDate: "2024-09-01",
      season: "Summer",
      description:
        "This course provides an introduction to astrophysics, including the structure and evolution of stars, galaxies, and the universe. Students will also learn about the techniques used in astronomical observations and data analysis.",
      studyType: "full-time",
      totalSeats: 30,
      seatsFilled: 20,
      contactHours: 22,
      school: ["School of Physics and Astronomy"],
    },
    {
      uuid: "40a31a09-7aa2-426f-a97b-60e7102333d7",
      courseTitle: "Introduction to Finance",
      professor: "Dr. John Smith",
      startDate: "2023-08-15",
      endDate: "2023-12-15",
      season: "Fall",
      description:
        "An introduction to the fundamental concepts and tools of finance, including time value of money, asset valuation, risk and return, and financial statement analysis.",
      studyType: "part-time",
      totalSeats: 50,
      seatsFilled: 30,
      contactHours: 15,
      school: ["School of Business"],
    },
    {
      uuid: "a3c7b3d0-77b7-4b77-92d3-872690a3aebc",
      courseTitle: "Data Science with Python",
      professor: "Dr. Maria Garcia",
      startDate: "2024-09-01",
      endDate: "2024-11-30",
      season: "Fall",
      description:
        "A hands-on course in data science using the Python programming language. Students will learn data manipulation, visualization, and machine learning techniques using popular Python libraries.",
      studyType: "full-time",
      totalSeats: 40,
      seatsFilled: 38,
      contactHours: 20,
      school: [
        "School of Computer Science",
        "School of Mathematics and Statistics",
      ],
    },
    {
      uuid: "81a82f72-bcbf-4086-8a8c-7c6141d4b89f",
      courseTitle: "World History",
      professor: "Dr. Jane Lee",
      startDate: "2024-02-01",
      endDate: "2024-05-30",
      season: "Spring",
      description:
        "A survey of the major events and developments in world history from ancient civilizations to the present day.",
      studyType: "part-time",
      totalSeats: 60,
      seatsFilled: 50,
      contactHours: 12,
      school: ["School of Humanities", "School of Social Sciences"],
    },
    {
      uuid: "2dd63e77-66f5-43c7-8ca8-0f91363c3d29",
      courseTitle: "Artificial Intelligence Ethics",
      professor: "Dr. Sarah Lee",
      startDate: "2024-09-15",
      endDate: "2024-12-15",
      season: "Fall",
      description:
        "This course covers the ethical considerations surrounding the development and use of artificial intelligence. Students will explore topics such as algorithmic bias, privacy concerns, and the impact of AI on society.",
      studyType: "part-time",
      totalSeats: 40,
      seatsFilled: 15,
      contactHours: 15,
      school: ["School of Computer Science", "School of Ethics and Philosophy"],
    },
  ],
};
