export const mockData = {
  course: {
    // length: "10 Weeks",
    // students: ["Student1", "student2", "etc"],
    // available: false,
    uuid: "61b3e62f-7fa9-4b0a-a069-4242cf1aa7cb",
    courseTitle: "Introduction to Computer Science",
    professor: "Dr. Jane Smith",
    startDate: "01-09-2023",
    endDate: "15-12-2023",
    season: "Fall",
    description:
      "This course introduces the fundamental principles of computer science, including programming concepts, algorithms, and data structures. Students will gain hands-on experience with a variety of programming languages and tools.",
    studyType: "full-time",
    totalSeats: 50,
    seatsfilled: 35,
    contactHours: 15,
    school: ["School of Computer Science"],
  },
  student: {
    studentID: 0,
    firstName: "Student",
    lastName: "1",
    email: "student1@email.com",
    school: "Liberal Arts",
    currentCourses: ["Intro to Courses"],
    completedCourses: [],
    enrolmentDate: "01/01/2000",
    graduationDate: "01/01/2001",
    graduated: false,
  },
  professor: {
    id: 0,
    fullName: "Dr. Michael Lee",
    firstName: "Michael",
    lastName: "Lee",
    email: "leeMic@onlineC+.edu",
    school: "School of Chemistry",
    courses: "School of Organic Chemistry",
    pre_nominals: "Dr.",
    idImage:
      "https://st3.depositphotos.com/6672868/13701/v/600/depositphotos_137014128-stock-illustration-user-profile-icon.jpg",
  },
};
